// ...existing code...
      <button class="socialgpt-participant-card-button analyze-card" data-card-index="${index}">${t('facebookParticipantAnalyzeUser')}</button>
      <button class="socialgpt-participant-card-button open-toolbox-card" data-card-index="${index}">${t('facebookParticipantOpenToolbox')}</button>
// ...existing code...
